apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testing3"
  annotations:
    backstage.io/techdocs-ref: dir:/home/windchill/sample-backstage-docs/docs

spec:
  type: service
  owner: guests
  lifecycle: experimental
