apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testing3"
  annotations:
    backstage.io/techdocs-ref: dir:C:\Users\Public\pratikpati1\docs
spec:
  type: service
  owner: guests
  lifecycle: experimental
